### ISSUE TITLE
AMBER parsers

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#10]
In line with the overall [API proposal](http://alchemlyb.readthedocs.io/en/latest/api_proposal.html), we want to have parsers for each of the major MD engines, and eventually have coverage for all of those in use. Since there are essentially two types of estimators (TI and FEP), each packages needs a parser for:
1. ~Extracting reduced potentials `u_nk` from output files (for FEP).~ (EDIT: This objective is postponed, emphasis right now  on TI. Open issue for `u_nk` when needed. — @orbeckst 2017-11-03)
2. Extracting derivatives `DHdl` from output files (for TI).

This issue is the nexus for discussion for such parsers for the **AMBER** package. If you have existing parsing code for this package, comment below and we can begin adapting it into the parsers outlined above in a PR.

**Comment by davidlmobley** [comment]
I'm checking with Ross Walker to see if he or someone in his group would want to be involved with this.

**Comment by davidlmobley** [comment]
@halx may also be interested.

**Comment by davidlmobley** [comment]
I have some response from Ross Walker and collaborators, including some sample files/scripts and potential future interest. I'm checking to see if I can post the info.

**Comment by dotsdl** [comment]
Excellent, thanks @davidlmobley! If you can post these components the best way might be to throw it in a repo so we have a place interested devs can pull from. I can also start hacking on it to see if we run into issues with the data structures we want all parsers to produce, which as you know is based heavily on GROMACS experience.

**Comment by davidlmobley** [comment]
From @danmermelstein, here is some AMBER material. Here's what he wrote to me:

> This sounds great! I don't really have time to contribute at the moment, but after I finish up the AMBER GPU alchemical free energy if you haven't found someone I, or someone I'm collaborating with on testing, could probably help. For now, theres a python script for getting and analyzing dvdl values from AMBER I've attached, as well as analyse.sh which essentially just calls getdvdl.py. However, I am considering revamping the way we output the dvdl values, because right now it's setup to just dump all of the results at the end of the run which requires saving all the values over the whole simulation.  And as far as FEP (or at least MBAR) we usually just use the PyMBAR suite, although I've not looked at this too much. 

I'm attaching his zip file. I'm a bit swamped today/tomorrow so I'm not dumping it into a repo right now, but feel free to put it wherever you want, @dotsdl .

[get_dvdl_AMBER.tar.gz](https://github.com/alchemistry/alchemlyb/files/764970/get_dvdl_AMBER.tar.gz)

**Comment by orbeckst** [comment]
Closed with PR #36.

**Comment by orbeckst** [comment]
Congratulations @shuail ! Excellent work and a major milestone done.
