### ISSUE TITLE
Add a `deduplicate` preprocessor

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#103]
See [this comment](https://github.com/alchemistry/alchemlyb/issues/101#issuecomment-630503665) for the context.

We are taking the approach of having [composable](https://en.wikipedia.org/wiki/Function_composition) preprocessing functions to make it easy for users to manipulate our `DataFrame`-based data structures without having to reinvent the wheel each time or quickly dive into complex and error-prone `pandas`-fu. To that end, we would like a preprocessor that simply and safely deduplicates records from our standard form DataFrames.

**Comment by xiki-tempula** [comment]
I think this is already done through the `drop_duplicates` keyword.
