### ISSUE TITLE
About reproducing the autocorrelation analysis in alchemical-analysis

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#106]
I'm interested in reproducing the autocorrelation analysis in `alchemical-analysis` using `alchemlyb`. However, I cannot seems to reproduce the `alchemical-analysis` result.
In `alchemical-analysis`, when using `--uncorr='dhdl'` on `alchemtest.gmx.benzene.Coulomb` gives
```
Number of correlated and uncorrelated samples:

 State            N          N_k        N/N_k

     0         3789         3789         1.06
```

When using alchemlyb
```
from alchemtest.gmx import load_benzene
bz = load_benzene().data
from alchemlyb.parsing.gmx import extract_u_nk
u_nk = extract_u_nk(bz['Coulomb'][0], T=300)
```
gives [4001 rows x 5 columns]
I have tried both `statistical_inefficiency` and `equilibrium_detection`, where 
```
from alchemlyb.preprocessing.subsampling import statistical_inefficiency
statistical_inefficiency(u_nk, u_nk[0])
```
gives [2001 rows x 5 columns]
and
```
from alchemlyb.preprocessing.subsampling import equilibrium_detection
equilibrium_detection(u_nk, u_nk[0])
```
gives [3976 rows x 5 columns]

So I wonder what is the correct way of reproducing the subsampling strategy used in `alchemical-analysis`.

**Comment by dotsdl** [comment]
Hey @xiki-tempula! Welcome to alchemlyb!

I'd like to dive into the codepath taken by your use of `alchemical-analysis`. We are interested in reproducing its results where possible and reasonable. Can you share with me the exact `alchemical-analysis` command-line usage you are using to produce those results?

**Comment by xiki-tempula** [comment]
@dotsdl Thank you for the reply. I have extracted the dhdl files from alchemtest.gmx.benzene.Coulomb and rename them as dhdl_0.xvg dhdl_1.xvg ... dhdl_4.xvg.
Then I run the cmd `alchemical_analysis.py -d ./ -p dhdl_ -f 10 -t 310 -s 0 -u kcal -w -g -o ./`

**Comment by dotsdl** [comment]
Excellent, thanks @xiki-tempula! This is very helpful.

**Comment by xiki-tempula** [comment]
@orbeckst I think we no longer want to ensure that they would output the same number of data, as so many things have changed.
