### ISSUE TITLE
"Advanced" GROMACS parsers needed?

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemlyb#11]
I'm guessing, @dotsdl , that your current GROMACS parsers only handle what I like to think of as "normal" alchemical free energy calculations where one runs simulations at a variety of lambda values (with our without Hamiltonian exchange). Is that correct? Presumably we would want this library to also be able to parse data for more "advanced" types of free energy calculations such as those @mrshirts has worked on, like Wang-Landau sampling and other expanded ensemble techniques which are enabled in GROMACS (e.g. one simulation spanning multiple lambda values). 

@mrshirts - is there someone in your group or elsewhere currently working on these techniques in GROMACS who would want to contribute parsers? We had some attempt to parse for this in `alchemical-analysis`, but since my group doesn't use these at all, maintaining/testing the code was problematic since things would change without us knowing about it. 

Alternatively, if there's not someone currently working with these methods in GROMACS we should put this on hold until someone who is wants to contribute and just proceed without expanded ensemble.

**Comment by mrshirts** [comment]
So, I have a new student that can be working on this relatively near future  (Travis Jensen).  He might take a little bit of time to come up to speed, though  Expanded ensemble parsing is relatively easy to do.  Alchemical-analysis did support it, but kept not supporting it when I turned my head.

I will have a bit more time over the next few months, so I will be more directly involved here.

**Comment by davidlmobley** [comment]
Excellent. So this is both a "yes, we need advanced parsers" and "yes, you guys can help with them", then? I can close this (since it was just a question) and create a separate issue. Does Travis have a github ID so I can tag him, @mrshirts ?

**Comment by mrshirts** [comment]
Travis is @trje3733. I'll let him know.  It might take a couple of months to getup to speed.

**Comment by dotsdl** [comment]
We might be able to accommodate this functionality in the existing parser functions, but to be able to tell I'd need at least one example file. Do you have an XVG with this type of data (or several, if that's what it takes) lying around that you can share, @mrshirts?

**Comment by davidlmobley** [comment]
@mrshirts - do you have an example of this type of data?

**Comment by davidlmobley** [comment]
Marking as closed since I created a separate issue for actually creating these parsers.
