### ISSUE TITLE
Add zenodo integration

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemlyb#12]
I'd like to add Zenodo integration for cite-able code DOIs. @dotsdl - any issues with that?

**Comment by dotsdl** [comment]
I'd love that. Not sure if I'm able to enable it, but if you do each release will get pulled and tagged with a DOI. Let me see if I'm able to do it and I'll let you know if I fail.

**Comment by davidlmobley** [comment]
@dotsdl - I just flipped the switch on zenodo, so I think we should be set. Do you want to do a release to test?

**Comment by davidlmobley** [comment]
(Or I can. Let me know your preferences.)

**Comment by dotsdl** [comment]
Let's wait for the pre-release. Making the milestone now. We're almost there, so hoping to get this out by end of next week.

**Comment by dotsdl** [comment]
Can you add the badge to the README, though?

**Comment by davidlmobley** [comment]
You don't get a badge until you do a release...

**Comment by dotsdl** [comment]
Oh I see. Well, we'll wait then. No worries.
