### ISSUE TITLE
Visualisation of overlap matrix

### ISSUE THREAD

**Issue by ncheron** [alchemistry/alchemlyb#127]
Hi,

I am trying to analyse results for FEP (for now, solvation free energy of acetate performed with Gromacs). I am using the scripts provided in https://alchemlyb.readthedocs.io/en/latest/visualisation.html. The forward and backward convergence works smoothly, so everything seems to be well installed. However, for the overlap matrix of the mbar I have this error:

Traceback (most recent call last):
  File "Plot2.py", line 14, in <module>
    ax = plot_mbar_overlap_matrix(mbar_coul.overlap_matrix)
  File "/home/ncheron/.local/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 116, in overlap_matrix
    return self._mbar.computeOverlap()['matrix']
TypeError: tuple indices must be integers or slices, not str

I am using python3.8, alchemlyb0.4.0 with pymbar3.0.3 (I have this issue https://github.com/choderalab/pymbar/issues/320 with pymbar3.0.5). Everything was installed locally on our cluster via python (from anaconda) and pip. Do you have some tips on how to solve this?

Thank you for you help.

Nicolas

**Comment by orbeckst** [comment]
I think the above error is related to alchemlyb requiring pymbar >= 3.0.5 https://github.com/alchemistry/alchemlyb/blob/4f95c28c87cd06067b4d2efd232bdb54726bde35/setup.py#L49 . 

Between 3.0.3 and 3.0.5 the return value of MBAR.computeOverlap() changed: 

**3.0.3** https://github.com/choderalab/pymbar/blob/095b746683840cb34e3fef51920519b46aa7654d/pymbar/mbar.py#L384-L396 : always returns dict and contains the "O" key

**3.0.5**  https://github.com/choderalab/pymbar/blob/1d14e80d3320a5ae0651fd002a8cb763a900190c/pymbar/mbar.py#L407-L427 : returns dict by default and contains the "matrix" key 


We are not likely going to implement hacks to be backwards compatible to 3.0.3. From my reading of https://github.com/choderalab/pymbar/issues/320 and the follow-up issue https://github.com/choderalab/pymbar/issues/419. 3.0.5 is not technically wrong so I don't see a reason to downgrade pymbar.

I think your best bet is to copy the code for the plotting code and make your own plotting code with the changes required to use your version of pymbar.

**Comment by ncheron** [comment]
Thank you for your answer. For some of my data set, I found a workaround by changing ~/.local/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py in this way (using pymbar3.0.5):
* Line 50/51 (that start with def __init__(self, ...)) were changed by removing "method='hybr'," and adding "solver_protocol=None,"
* Line 56 ("self.method = [dict(method=method)]") was removed and instead I added "self.solver_protocol=solver_protocol"
* Line 84 ("solver_protocol=self.method,") was removed and instead I added "solver_protocol=self.solver_protocol,"

However, it doesn't solve everything and some data set were still causing the same problem. I then switched from Gromacs2019.4 to Gromacs2021, and then all my problems have disappeared.

Nicolas
