### ISSUE TITLE
Implement minimal TI estimator

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#13]
We would like to ship a minimal TI estimator with the first pre-release, since getting this to work will solidify the structure of the `dHdl` data structure that all parsers will need to produce. At a minimum, it requires a `fit` method and attributes yielding the `delta_f_` dimensionless free energy matrix and `d_delta_f_` uncertainties.

**Comment by orbeckst** [comment]
Just as a note: PR #20 only calculates standard error of the mean of the dH/dl and does not take correlations in the data into account so these are technically not proper error estimates for dF.

**Comment by dotsdl** [comment]
@orbeckst we won't be taking correlations into account in the estimators at this time, but perhaps in the future we can add these in. Right now we are designing the estimators in such a way that they assume the data given to them is subsampled already in such a way that it is relatively uncorrelated.
