### ISSUE TITLE
docs got lost

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#136]
See https://github.com/alchemistry/alchemlyb/commit/3ae6668ec323420ca8d14b206534c94fffc5ae91

**Comment by xiki-tempula** [comment]
For later on, is it discouraged to manually write doc for none top-level rst files (such as estimators/alchemlyb.estimators.BAR.rst)? The doc should be moved to the corresponding py files instead?

**Comment by orbeckst** [comment]
We use the [sphinx autosummary extension](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html). I am not super-familiar with it. The stub files that it generates should not be edited manually because by default they are overwritten. We could disable overwriting stub files although I'd rather figure out a way to have all automatic stuff continue to work automatically with as little human interference as possible.

Can you see if adding the docs to the Python files will add them to the generated files?

**Comment by orbeckst** [comment]
Looking at 3ae6668, we must have manually edited the stub pages for quite a while. If we set [autosummary_generate_overwrite](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_generate_overwrite) to `False` then we only generate these pages once and then have to manually maintain them.

Is this preferable?

**Comment by xiki-tempula** [comment]
Yes, I think autosummary_generate_overwrite=False is the best way to go.

**Comment by orbeckst** [comment]
I'll disable it and revert. I have to do it on a separate branch so that I can publish a fixed 0.4.2.
