### ISSUE TITLE
port CI to GitHub actions

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#139]
Switch from Travis CI to GitHub actions.

**Comment by dotsdl** [comment]
I can handle this one. Added to list for this weekend.

**Comment by orbeckst** [comment]
@alchemistry/alchemlyb — The CI on travis-ci.org stopped working on June 15 because we did not migrate to travis-ci.com. Either we migrate (not sure if I have the power to do so) or we get the move to GH actions done quickly. But at the moment development on alchemlyb is at a halt.

**Comment by dotsdl** [comment]
Got it, apologies, wasn't able to get to this this weekend. Putting it together now.

**Comment by dotsdl** [comment]
#142 is one proposed solution.
