### ISSUE TITLE
Implement advanced (e.g. expanded ensemble) parsers for GROMACS/provide sample data

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemlyb#14]
As per #11 , we need some more advanced parsers for expanded ensemble and other more sophisticated free energy calculations for the GROMACS side of things. @mrshirts and @trje3733 will help with this, though the likely timescale is a couple of months.

Progress could perhaps be made sooner if sample XVG files could be provided. @mrshirts , are you currently doing these calculations or do you know anyone who is, so we could get some samples?

**Comment by mrshirts** [comment]
I have a set of xvg files that cover a lot of these cases.  What's the best way  to get them to you?

**Comment by davidlmobley** [comment]
If they're small, @mrshirts , you can upload a zip here. Otherwise, you should put in Google Drive or Dropbox or something similar (someplace that gives you a shareable URL) and put the URL here.

**Comment by mrshirts** [comment]
Working on it.  Trying to figure out why alchemical-analysis is having issues parsing these files now.

**Comment by davidlmobley** [comment]
@mrshirts - that's part of why I want things to come in through `alchemlyb`. I'm fairly convinced alchemical-analysis needs a complete rewrite/rearchitecting to be really maintainable, and I'd like it to rely on `alchemlyb` to get data IN and to drive analysis. Then it would just add bells and whistles on top of `alchemlyb`.

**Comment by mrshirts** [comment]
[test_alchemical.zip](https://github.com/alchemistry/alchemlyb/files/789354/test_alchemical.zip)

OK, here we go.  Some test files, plus the output from alchemical_analysis.py.  I'm happy to explain anything that doesn't make sense, or how alchemical_analysis.py is doing the parsing.

**Comment by orbeckst** [comment]
Once  @trje3733 is eligible as an assignee, add him to the issue.

**Comment by orbeckst** [comment]
@trje3733 do you have any questions on how to proceed? Would it help to discuss next Monday at the scheduled conference call?

**Comment by orbeckst** [comment]
@trje3733 I only just realized that you opened alchemistry/alchemtest#16... looking at it now. (see also https://github.com/alchemistry/alchemtest/pull/16#issuecomment-346246072 to get quicker reactions)
