### ISSUE TITLE
adopt NEP29 for support of Python versions

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#140]
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) describes a time-based deprecation policy for scientific python projects for which versions of Python (and numpy) to support. 

> When a project releases a new major or minor version, we recommend that they support at least all minor versions of Python introduced and released in the prior 42 months from the anticipated release date with a minimum of 2 minor versions of Python, and all minor versions of NumPy released in the prior 24 months from the anticipated release date with a minimum of 3 minor versions of NumPy.

We also depend on pandas but the [panda's Python Policy](https://pandas.pydata.org/docs/development/policies.html#python-support) is not clear, except
> pandas will only drop support for specific Python versions (e.g. 3.6.x, 3.7.x) in pandas major or minor releases.

For example, pandas 1.2 does not  support Python 3.6 anymore (which reaches [end of support](https://www.python.org/downloads/)  2021-12-23) and [fell out of the NEP29 range in Nov 2020](https://numpy.org/neps/nep-0029-deprecation_policy.html#detailed-description).

**alchemlyb heavily relies on pandas and numpy** (and **pymbar**). To keep the maintenance burden manageable we propose to effectively follow the support roadmap of our major upstream dependencies. 

----

For the new units code #125 we really want to use pandas ≥ 1.2 because earlier support for pandas.DataFrame.attrs is very buggy. This means that we would drop Python 3.6 support for the next minor release (0.5.0) in addition to having already dropped 2.7 and 3.5 #130.  

----
Maybe useful [nep29-calculator](https://pypi.org/project/nep29/)

**Comment by orbeckst** [comment]
@dotsdl @davidlmobley are you ok with a more aggressive deprecation policy?

**Comment by orbeckst** [comment]
@mrshirts what is the Python deprecation policy for pymbar?

**Comment by davidlmobley** [comment]
I am, definitely. Supporting the most recent two versions seems reasonable to me.

**Comment by xiki-tempula** [comment]
As is discussed in #125, I'm thinking of using `DataFrame.attrs` to store the metadata such as `energy_units` and `temperature`. `DataFrame.attrs` is a new feature under active development (https://github.com/pandas-dev/pandas/issues/28283).

Pandas adopted NEP29 and has dropped the support for py36 so many of the "new" features would only support py37-py39. If we wish to support py36, which is no longer supported by pandas, custom functions need to be written to port these features to alchemlyb, which would result in code redundancy that needs to be removed when we eventually dropped py36.

**Comment by dotsdl** [comment]
Totally in favor of this. I've been advocating for NEP29 adoption within the OpenFF and QCArchive ecosystems, and I think it comes with more benefits than drawbacks by a mile.

**Comment by davidlmobley** [comment]
Totally agree with this; this is a strong argument to drop Py36 support. Code redundancy is a problem.

**Comment by orbeckst** [comment]
Thank you all for your opinions. More comments are welcome.

I think we have enough arguments in favor of **adopting NEP29 for alchemlyb** (and alchemtest).

**Comment by orbeckst** [comment]
I'll update code and docs accordingly.
