### ISSUE TITLE
Release 0.4.2 has no Zenodo DOI

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#143]
It looks as if Zenodo got stuck while creating the DOI for release 0.4.2.

![Screenshot from 2021-06-15 16-56-59](https://user-images.githubusercontent.com/1326811/122138051-cbd23080-cdfa-11eb-8aab-ea2fc37f00b7.png)

I'm not sure if there is a procedure for kicking it?

**Comment by orbeckst** [comment]
I don't know. I don't control the Zenodo integration for alchemlyb.

It's a bit annoying but at least 0.4.2 has no functional differences to 0.4.1, just updated docs.

Hopefully, 0.5.0 will fix that.

**Comment by xiki-tempula** [comment]
From the GitHub site, there is nothing controlling it as far as I know.

**Comment by orbeckst** [comment]
I checked again and 0.4.2 now has a zenodo package https://zenodo.org/record/4973744 so I am closing.
