### ISSUE TITLE
Error estimates for TI calculations, and replicate support. 

### ISSUE THREAD

**Issue by josiahbones** [alchemistry/alchemlyb#144]
Hi there!

Apologies if these questions have been answered elsewhere.

I am just enquiring as to the definition of the error estimates output by the TI fit code, in particular, d_delta_f_.

Is this the accumulative standard error of the entire set of data in the fit, as is typically reported in TI publications? 

One other question, is alchemlyb capable at this time of correctly giving combined results (mean and SEM) for multiple independent replicates? 

Thanks for your help, and special thanks to anyone working on this code, it has already made my analysis much smoother.

**Comment by xiki-tempula** [comment]
Hi,

> Is this the accumulative standard error of the entire set of data in the fit, as is typically reported in TI publications?

Yes.

> One other question, is alchemlyb capable at this time of correctly giving combined results (mean and SEM) for multiple independent replicates?

No, but the mean and SEM could be calculated easily once the estimate for each repeat is done.
```
data = [repeat1, repeat2, repeat3]
mean = np.mean(data)
sem = np.var(data)/len(data)
```

**Comment by u5459577** [comment]
Thanks for your reply Xiki. In the above example, are the repeats the actual TI fit estimate objects? In this example, when I do what you have proposed, I end up with an error "unsupported operand type(s) for +: 'TI' and 'TI'" upon trying to calculate the accumulative mean. Or are you proposing to just calculate a new mean and sem from just replicate means? I didn't think this would correctly capture the propogation of error.

**Comment by xiki-tempula** [comment]
@u5459577 Thank you for the reply. I see your point now.

To access the result from the estimator object, please find the information in 
https://alchemlyb.readthedocs.io/en/latest/estimators-fep.html#list-of-fep-based-estimators
https://alchemlyb.readthedocs.io/en/latest/estimators-ti.html#list-of-ti-based-estimators

The calculation of mean and SEM is currently not implemented in the alchemlyb as it is a bit unclear which is the best way of doing this. Some people (me) thinks it is more clear to just do a simple mean and SEM as each estimate is an independent observation but obviously you are welcome to use your own way of calculating the result.

**Comment by xiki-tempula** [comment]
Close due to inactivity.
