### ISSUE TITLE
Possible improvements for the NAMD parser

### ISSUE THREAD

**Issue by jhenin** [alchemistry/alchemlyb#145]
To make the NAMD parser more robust:

- [x] use lambda values from "NEW WINDOW" lines, and checking the corresponding "Free energy" end-of-window line
- [x] warn about incomplete files missing either of those lines
- [ ] If the end of window line is missing (truncated simulation), check that at least the post-equilibration data is not empty
- [ ] ~~warn about missing lambda values in the final dataset~~

**Comment by orbeckst** [comment]
Is this issue related to PR #135  or is it more a todo list?

**Comment by jhenin** [comment]
It's a todo list for enhancements. That said, this [upcoming contribution](https://github.com/jhenin/alchemlyb/pull/2) by @ttjoseph will probably check most of these.

**Comment by orbeckst** [comment]
Nice, looking forward to the PR. Please feel free to ping @orbeckst @xiki-tempula to get attention when the PR is up.

**Comment by jhenin** [comment]
@orbeckst I would say this is far enough in "nice to have" territory that it's not enough to keep this issue open.
