### ISSUE TITLE
docs are not built on RTD for a PR

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#156]
The ["Build pull requests for this project "](https://docs.readthedocs.io/en/stable/pull-requests.html) (under *Advanced Settings* on Read the Doc) should be enabled for alchemlyb. The corresponding webhook/integration should be enabled.

See also https://github.com/alchemistry/alchemtest/issues/54

**Comment by orbeckst** [comment]
The setting is checked on RTD but something isn't working with the integration.

**Comment by orbeckst** [comment]
Please see https://docs.readthedocs.io/en/stable/connected-accounts.html#github-permission-troubleshooting

You can also try rsyncing the [webhook](https://docs.readthedocs.io/en/stable/webhooks.html). On RTD go to the alchemtest project -> Admin -> Integrations: [GitHub incoming webhook](https://readthedocs.org/dashboard/alchemlyb/integrations/131121/): **Resync webook**

>  This integration is being managed automatically by Read the Docs. If it isn't functioning correctly, try re-syncing the webhook:
> 
> [readthedocs.org/api/v2/webhook/alchemlyb/131121/](https://readthedocs.org/api/v2/webhook/alchemlyb/131121/)

When I try it, I get an error 
> Webhook activation failed. Make sure you have the necessary permissions. 

Could someone with admin permissions on the alchemistry org please try that, e.g. @davidlmobley @dotsdl ?

**Comment by mikemhenry** [comment]
:wave: @dotsdl if you add me (`mmh`) to the RTD project I can take a look at this, I recently fixed this issue in `openmmtools`

**Comment by dotsdl** [comment]
Added! Thank you for your help in maintaining these pipes @mikemhenry. Looking at this now as well.

**Comment by dotsdl** [comment]
@davidlmobley, @mrshirts, or @jchodera, would you mind adding me as an org Owner for `alchemistry`? @mikemhenry and I suspect (though aren't completely sure yet) that our ReadtheDocs issues are due to not having org-level OAuth permissions in place for ReadtheDocs, and I can't adjust these without the org-level Owner role.

**Comment by dotsdl** [comment]
See commentary in #195: we now have org-level authorization for ReadtheDocs that allows RTD to include a PR check linking to the doc build. Webhooks for both `alchemlyb` and `alchemtest` are working as expected.

Thanks to @mikemhenry for invaluable help in untangling this. Sorry for the long delay @orbeckst!
