### ISSUE TITLE
Remove GromacsWrapper dependency from alchemlyb.parsers.gmx

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#16]
We currently use the `gromacs.fileformats.XVG` class for parsing out data from XVG files in the `alchemlyb.parsers.gmx` module. This works well, but it means [GromacsWrapper](https://github.com/Becksteinlab/GromacsWrapper) is a dependency and it is not yet working under [Python 3](https://github.com/Becksteinlab/GromacsWrapper/issues/44). This holds back `alchemlyb` from full Python 3 support.

I recommend implementing a helper function in `alchemlyb.parsers.gmx` that parses out the raw tabular information of an XVG file similarly to how the GromacsWrapper XVG class does this in its `XVG.to_df()` method. We cannot outright lift the code from GromacsWrapper due to its licensing, but we can reimplement the (minimal) functionality we need here.

**Comment by orbeckst** [comment]
I think this can be closed after the merge of #19.
