### ISSUE TITLE
Add `openany` context manager for decompression of bzip2, gzip, zip, etc.

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#17]
We want parsers to be able to support parsing files that are compressed using common compression utilities, such as `bzip2`, `gzip`, `zip`, `rar`, etc. This is easy enough to support by building a context manager such as [`openany`](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/lib/util.py#L224) like that found in MDAnalysis. We cannot directly lift the code from MDAnalysis due to incompatible licensing, but we can implement our own simplified version of this mechanism for use by all parsers.

**Comment by orbeckst** [comment]
I think this can be closed: there's now `parsing.util.anyopen`.

**Comment by orbeckst** [comment]
Completed in 68edb8a440ced8702cc458d6f7af70def64cb666
