### ISSUE TITLE
Remove the alchemlyb.concat when the dependency for pandas raise to v1.4.0

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#179]
WIth https://github.com/pandas-dev/pandas/pull/42252,
The pandas.concat is fixed from v1.4.0 (at the develop branch), so I placed the issue here to remind me to remove alchemlyb.concat when we raise the dependency of pandas to v1.4.0.

**Comment by orbeckst** [comment]
That's good news!

**Comment by orbeckst** [comment]
... and awesome, it's _your_ contribution to pandas. Well done!

**Comment by orbeckst** [comment]
We'll have to **deprecate** `alchemlyb.concat` and then remove one or two releases in the future.

**Comment by xiki-tempula** [comment]
@orbeckst I have checked and I think we might need to deprecate the py3.7 as well.

**Comment by orbeckst** [comment]
That depends on NEP29 — of the top of my head I don't remember when 3.7 drops off.

**Comment by xiki-tempula** [comment]
@orbeckst Sorry, I wonder if we can retain the support for py3.7 for some time? The openeye workflow that I uses still pins the python version to 3.7.

**Comment by orbeckst** [comment]
Also, Google Colab only uses 3.7....

**Comment by xiki-tempula** [comment]
@orbeckst I could depreciate py3.7 now. With regard to alchemlyb.concat, do we add a deprecation warning now and depreciate it in 1.0.0 or we just depreciate it?

**Comment by orbeckst** [comment]
Previously you lobbied to keep 3.7 around, now you're happy to remove it. What made you change your mind?

For alchemlyb.concat, you need to add a deprecation warning on it and the earliest it can be removed is in the next minor release update or in 1.0.

**Comment by xiki-tempula** [comment]
@orbeckst 

> Previously you lobbied to keep 3.7 around, now you're happy to remove it. What made you change your mind?

Company RSE decides to update the software stack to py3.8 so my code that uses alchemlyb is no longer pinned to py3.7.

**Comment by orbeckst** [comment]
In PR #214 we updated `alchemlyb.concat()` to use the `pandas.concat()` version but we decided **to keep `alchemlyb.concat()`** because it has additional error checking.
