### ISSUE TITLE
Support Python 2?

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#18]
The scientific Python development community is very much in favor of dropping support for Python 2 in the next year, since supposedly advances in Python 3 make it harder to justify trying to maintain Python 2 compatibility. Being aware that much of the scientific Python user community is a good deal slower in adopting Python 3, there's certainly an argument for doing our best to make sure everything we do in ``alchemlyb`` works for Python 2. However, this does cost limited development time and effort.

What is the current feeling here? Do we proceed trying to support both, or go for broke with Python 3 without looking back?

**Comment by davidlmobley** [comment]
I'm fine with dropping support for Python 2. And I say that as a recent transitioner. One day I ran into something which would only work on Python 3, so I just pulled the trigger and moved everything over via `conda`. It really only took a short time.

**Comment by orbeckst** [comment]
I'd like to keep Python 2 for the moment.

**Comment by dotsdl** [comment]
Okay, for now we'll move forward with maintaining support for Python 2. I think we can do this so long as libraries such as ``pandas``, ``numpy``, and ``sklearn`` continue to do so, but once they drop support it will be hard to continue it here.

**Comment by orbeckst** [comment]
I agree. 

--
Oliver Beckstein
email: orbeckst@gmail.com
