### ISSUE TITLE
Convergence not installing via pip

### ISSUE THREAD

**Issue by csbrasnett** [alchemistry/alchemlyb#180]
I'm trying to install alchemlyb via pip into a clean virtual environment, and everything's installing as expected, except the convergence tools. When I look in the installation directory, the files are present, but empty.

pip: 21.3.1
ubuntu: 20.04.3
Python: 3.8.10

**Comment by xiki-tempula** [comment]
@csbrasnett Thanks for the reporting. I wonder if do you mean install the github version with pip `pip install .` or install the release like `pip install alchemlyb`

**Comment by csbrasnett** [comment]
@xiki-tempula by the latter method. Installing with `pip install -e ./` from the github version works fine thanks.

**Comment by xiki-tempula** [comment]
@csbrasnett Thanks. The Convergence function is not in the release yet. So if one install the pip release the function is not there yet.

**Comment by csbrasnett** [comment]
Thanks for the help @xiki-tempula!
