### ISSUE TITLE
Nan in the load_expanded_ensemble_case_1 dataset

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#185]
One would assume that there shouldn't be any NaNs in the test data set, but simply removing the NaNs from the load_expanded_ensemble_case_1 dataset would make some tests fail. See #184

**Comment by orbeckst** [comment]
Do you suspect that there's something wrong with the data?

**Comment by xiki-tempula** [comment]
@orbeckst I think there are NaNs in the dataset as dropna would alter the size of the dataset.

**Comment by orbeckst** [comment]
Did you check that this is what happens? Then the next stage would be to contact the original authors to verify that these nans belong there. Once this is all confirmed we can consider changing the test answers.

**Comment by orbeckst** [comment]
@xiki-tempula please remind me, what do we have to do here? In PR #184 we learned that the NAN should not really be in the dataset. But with #171  solved (PR #183) we can use the dataset. 

Maybe we only need to add a note in alchemtest that the dataset contains NAN?

**Comment by orbeckst** [comment]
Nothing else to do here...
