### ISSUE TITLE
use pymbar 3.0.6

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#187]
There's a bug fix release of pymbar https://github.com/choderalab/pymbar/releases/tag/3.0.6 and they are now also on conda-forge.

- [x] test that 3.0.6 didn't break anything in alchemlyb
- [x] review [3.0.6 changes](https://github.com/choderalab/pymbar/releases/tag/3.0.6)
- [x] review installation process (conda package?)

**Comment by xiki-tempula** [comment]
I think pymabr 3.0.6 is not changing anything. All the tests are passing.
I wonder what is review installation process (conda package?)?

**Comment by orbeckst** [comment]
I wanted to check if we want to switch our CI over to use conda. But for right now everything works fine (and fast) with pip so let's keep it.

We should, however, consider putting alchemlyb on conda-forge, now that one of our main dependencies is also there.

**Comment by orbeckst** [comment]
SOrry @xiki-tempula , just read too fast... given that you started using conda in CI I'll have a look at PR #191.
