### ISSUE TITLE
Support AutoMBAR in forward and backward convergence

### ISSUE THREAD

**Issue by VOD555** [alchemistry/alchemlyb#189]
I currently have a data set which can only be analyzed by autombar (related to one issue in pymber https://github.com/choderalab/pymbar/issues/419 ). I want to get the forward and backward convergence plot using mbar, and I found the current version doesn't support autombar in convergence analysis. 
It would help if it's supported.

**Comment by xiki-tempula** [comment]
@VOD555 Thanks for the suggestion, I will add this option tonight.
