### ISSUE TITLE
Conda release

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#192]
I'm thinking of making a conda release. I wonder where do we want to release it to?
Conda-forge, bioconda or Omnia?

**Comment by orbeckst** [comment]
conda-forge

**Comment by xiki-tempula** [comment]
@jan-janssen Many thanks for porting the alchemlyb to conda-forge and your contribution is very much appreciated.
I think it would be even more helpful if you could open an issue in the alchemlyb before porting it to conda-forge so we could update the doc accordingly.
In addition, it might be better that for the conda feedstock, the tarball file is pulled from github instead of the pypi, so we can have centralised management of the distributions.

**Comment by orbeckst** [comment]
Does a feedstock already exist? Can you link it here?

pulling from PyPi is fine with me, that’s how we do it with MDAnalysis, the regro cf autotick bot will then also easily create new releases automatically (might also work with GitHub tar balls, not sure).

**Comment by xiki-tempula** [comment]
@orbeckst It is this one https://github.com/conda-forge/alchemlyb-feedstock.

**Comment by jan-janssen** [comment]
@xiki-tempula , @orbeckst  I am happy to add you both as maintainers to the conda feedstock. Just give me a quick feedback who I should add. 

Regarding building from pypi, the main advantage is that conda then knowns to look for a `setup.py` file, so we can automate a lot of the processes on the conda site. But once the recipe is generate I am also fine with using the GitHub repository.

**Comment by orbeckst** [comment]
@jan-janssen can you please add me as a maintainer?

building from PyPi is totally fine with me.

**Comment by orbeckst** [comment]
@jan-janssen do you have a twitter handle that you want mentioned when I tweet about alchemlyb next time? Many folks will be very happy to hear that there‘s conda support available.

**Comment by jan-janssen** [comment]
Done - and yes I have a Twitter account - `@Jan_J` but I rarely use it these days.

**Comment by orbeckst** [comment]
Thanks!

**Comment by orbeckst** [comment]
I updated https://github.com/alchemistry/alchemlyb/wiki/Developer-Guide#release-management with the conda-forge information. 

We should add some badges to the README and some information to the installation instructions that conda packages are available.

**Comment by orbeckst** [comment]
I tried a fresh `conda install alchemlyb` on macOS-64 with python 3.9 but only managed to install 0.6.0, even though the 0.7.0 package is available at https://anaconda.org/conda-forge/alchemlyb/files .  Does anyone here (or @IAlibay ) been able to install the 0.7.0 conda package?

**Comment by IAlibay** [comment]
> I tried a fresh `conda install alchemlyb` on macOS-64 with python 3.9 but only managed to install 0.6.0, even though the 0.7.0 package is available at https://anaconda.org/conda-forge/alchemlyb/files . Has anyone here (or @IAlibay ) been able to install the 0.7.0 conda package?

Looks like a major outage for conda-forge's CDN cloning pipeline: https://conda-forge.org/status/

I suspect there will be a backlog in new packages until it's resolved.

**Comment by jan-janssen** [comment]
The issue seem to be fixed now - can you test it again.

**Comment by IAlibay** [comment]
Looks good to me!
```
──────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────

  + alchemlyb    0.7.0  pyhd8ed1ab_0      conda-forge/noarch        53kB
  + nomkl          1.0  h5ca1d4c_0        conda-forge/noarch         4kB
  + numexpr      2.8.3  py38h97b1c41_100  conda-forge/linux-64     138kB
  + pymbar       3.0.7  py38h71d37f0_0    conda-forge/linux-64     123kB
  ```

**Comment by orbeckst** [comment]
Worked for me, too!

Thank you, everyone.
