### ISSUE TITLE
release 1.0

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#208]
Create a 1.0 release (we have a reasonably stable API). 

* This would be the last release that supports pymbar 3 (see #205 ).
* Should contain the ABFE workflow.

[Release management](https://github.com/alchemistry/alchemlyb/wiki/Developer-Guide#release-management)
- [x] updated CHANGES
- [x] tagged 1.0.0
- [x] checked testpypi version
- [x] created release on GitHub
- [x] created conda package (reviewed and merged the cf-regro commit to the conda-forge repo for the conda package)
- [x] announced in forum

**Comment by orbeckst** [comment]
@xiki-tempula @DrDomenicoMarson what should be accomplished before we can release a 1.0? Those issues/PRs should be added to the [1.0.0 milestone](https://github.com/alchemistry/alchemlyb/milestone/7).

**Comment by orbeckst** [comment]
Sounds sensible. Could you please adjust the milestone tags as necessary, @xiki-tempula ?

**Comment by DrDomenicoMarson** [comment]
I think we need to have a somewhat definitive solution/workaround for issue #242 before 1.0.0, I'm waiting for a definitive response from AMBER developers. Tomorrow I'll better explain the situation in the relevant thread, and I'll try to propose a reliable solution!

**Comment by xiki-tempula** [comment]
@DrDomenicoMarson The 1.0.0 is just to make the API stable. For #242, if it is too difficult, we could just do a 1.0.1. But it would be really helpful if this could be done before 1.0.0.

**Comment by xiki-tempula** [comment]
I'm fine with a 1.0 release. As usual, I would imagine that 1.0.1 release will soon follow.

**Comment by orbeckst** [comment]
The [1.0.0 release](https://github.com/alchemistry/alchemlyb/releases/tag/1.0.0) is now available. It should be on conda-forge within a day or so.

@DrDomenicoMarson do you have a twitter handle so that I can give you some credit in the announcement tweet?

**Comment by DrDomenicoMarson** [comment]
Wow, that was quick :-)
My Twitter handle is DomenicoM87!

**Comment by orbeckst** [comment]
Thanks. I am still waiting for conda-forge https://github.com/conda-forge/alchemlyb-feedstock/ (there's an automated process that creates a PR from the PyPi package but it typically has a couple of hours backlog)

**Comment by orbeckst** [comment]
Manually working on the cf package in https://github.com/conda-forge/alchemlyb-feedstock/pull/6

**Comment by orbeckst** [comment]
Cf package for 1.0.0 is now available https://anaconda.org/conda-forge/alchemlyb/files

**Comment by orbeckst** [comment]
All done, I even tweeted about it.
