### ISSUE TITLE
Amber parser incorrectly set the time when reading dHdL/ u_nk values

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemlyb#221]
Hello everyone, this is the first time for me contributing to anything on GitHub, I hope I haven't done anything wrong 😄 
I think how the current parser computes the time value for each value of dHdL/u_nk is wrong. Currently, the logic is like this:
```
file_datum.t0 + (frame_index + 1) * file_datum.dt * 1000
```
where the ```1000```is arbitrary as far as I understand (it's stated that is a unit conversion, but that's not true).

This is not a big deal when we are reading just from a single file, because the time index will monotonically increase anyway, but problems arise when we try to concatenate multiple dataframes coming from continuations from the same simulation. What's happening is that every time a new output file is read, the "time origin" is read from the file itself, and so it's reset, and from here the time is correctly "increased". Concatenating these files will easily produce wrong dataframes with incorrect/duplicate time indexes. 

It happened to me, that I had simulations with dt=0.002 ps, ntpr=500 steps, and restarting every 5 ns, so the output file from every simulation had 5000 values of dHdL/u_nk. When importing two consecutive output files:
- the first df had time indexes of 2,4,...9998,10000
- the second df had time indexes 5002,5004...14998,15000
- concatenating the two files I had duplicated time indexes, and preprocessing such as equilibrium detection failed. 

AMBER's pmemd/sander writes output information every ```ntpr``` timesteps, and so we are reading dHdL/u_nk values at this interval. The correct logic should be to multiply the index by the timestep, as it's already done, and then by this ```ntpr``` value. In this way, the time is correctly computed.

Interestingly enough, the FEData object already read the ```ntpr``` value from the AMBER output file, it's just then discarded and not saved as an attribute of the object, and never used. 

So to fix this I suggest just adding ```ntpr``` to FEDdata ```__slots__```, add the read ```ntpr``` value as an attribute to the object, and then just change the time computation to
```
file_datum.t0 + (frame_index + 1) * file_datum.dt * file_datum.ntpr
```

**Comment by xiki-tempula** [comment]
Thanks for raising an issue. This looks reasonable.

I think a test would be where you read the amber output file from https://github.com/alchemistry/alchemtest and check if the time of row 10 (or any arbitrary row) will give the time that you expect it to have.
