### ISSUE TITLE
AMBER: why are we reading AMBER output averages (and not using them)?

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemlyb#226]
AMBER output can optionally report every ```ntave``` steps (if != 0) the average of dHdl and other parameters. 
Right now parsing dHdl we are collecting these values (here we are also collecting different components reported by AMBER), but we are not using any of this information at all in the code. Maybe it was a leftover from copying from ```alchemical-analysis```?. 

I think we could just skip the reading of the averages since we are collecting all the values (and the user usually performs better equilibration/subsampling analysis after reading all the data).

TO DO:
  - Skip the lines reporting the AVERAGES, instead of uselessly collecting them.

**Comment by orbeckst** [comment]
I am happy with removing the data-reading that is not needed.

**Comment by DrDomenicoMarson** [comment]
Great, I will address all these issues in some order, one at a time, to make the review process easier!
