### ISSUE TITLE
AMBER: regarding #FIXME and #NOTE about reading integers/float while parsing files

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemlyb#229]
Here is the incriminated code:
```python
        result = []
        for field in fields:
            match = re.search(r' %s\s+=\s+(\*+|%s|\d+)'
                              % (field, _FP_RE), line)
            if match:
                value = match.group(1)
                # FIXME: assumes fields are only integers or floats
                if '*' in value:  # Fortran format overflow
                    result.append(float('Inf'))
                # NOTE: check if this is a sufficient test for int
                elif '.' not in value and re.search(r'\d+', value):
                    result.append(int(value))
                else:
                    result.append(float(value))
            else:  # section may be incomplete
                result.append(None)
        return result
```

--- regarding the # FIXME:

It's right that we are assuming here that the values parsed are just int/float, but indeed everything we are interested in reading here is just int or float values. ```value``` starts as a string, if I understand correctly ```value = match.group(1)```, so I can see two options here:
a) catch the exception that ```float(value)``` will throw at us if ```value``` can't be converted to a ```float``` and raise an informative exception
b) catch the exception as well, but instead of raising an exception, we append to ```result``` just the string value of ```value```

I think both scenarios work because right now no errors are reported of this function trying to transform an invalid string to a float.  If we raise an informative exception it could be interesting because if anyhow AMBER format will change and the parser will break here, we have an exception that will pinpoint the problem for us. If we go with b), no exception will be raised, but maybe we'll be getting something we don't want in ```result``` without any warning. If we'll make some changes to the code that requires ```string``` values from AMBER output in case a) we'll just need to change the code here, anyway.

--- regarding the # NOTE
I think the code here is needlessly "complicated". Wouldn't be easier to read something like:

```python
            if match:
                value = match.group(1)
                if '*' in value:  # Fortran format overflow --- that's right, we really need to catch * values!
                    result.append(float('Inf'))
                # NOTE: maybe a better catcher for int/float
                else:
                    try:
                        result.append(int(value))
                    except ValueError:
                        result.append(float(value))
            else:  # section may be incomplete
                result.append(None)
        return result
```

Let me know what you think about this changes!

**Comment by xiki-tempula** [comment]
I'm not an amber expert so I don't know what kind of tricky cases there will be. I think a good thing to do might be trying to get some wrongly formatted AMBER output to alchemtest and show that the parser gives the desirable result.

**Comment by DrDomenicoMarson** [comment]
The "wrongly formatted" AMBER files in alchemtest are some artifacts, handmade files, that were created when the tests were made, I don't know by who. In fact, they don't represent (almost any of them) real-case scenarios of wrongly formatted AMBER files :-)
They are tailor-made just to make some tests fail, but real-life files like that will never be met.

Making the changes I proposed I know will pass all tests we have now, as I already tried.

**Comment by DrDomenicoMarson** [comment]
I can't think of many trick cases of wrongly formatted AMBER files, maybe we could be more precise in the testing, not check if different sections of the output file are present (it's really hard to find an Amber file that doesn't have a "CONTROL" section, it could happen only if someone had hand-edited it). The more precise test should test if:
- is effectively a TI/MBAR simulation
- there are the right number of lambda windows/MBAR windows
- the simulation is actually finished

**Comment by xiki-tempula** [comment]
> The "wrongly formatted" AMBER files in alchemtest are some artifacts, handmade files, that were created when the tests were made, I don't know by who. In fact, they don't represent (almost any of them) real-case scenarios of wrongly formatted AMBER files :-)
> They are tailor-made just to make some tests fail, but real-life files like that will never be met.
> 
> Making the changes I proposed I know will pass all tests we have now, as I already tried.

I'm not an AMBER expert so I cannot comment on whether these tests are real or not. But I'm happy as long as the current tests passed.

> I can't think of many trick cases of wrongly formatted AMBER files, maybe we could be more precise in the testing, not check if different sections of the output file are present (it's really hard to find an Amber file that doesn't have a "CONTROL" section, it could happen only if someone had hand-edited it)

I'm fine with not having new tests. As long as the new PR could pass the existing tests, I'm happy.

**Comment by DrDomenicoMarson** [comment]
Great, so I'll make this change after my last PR #230 is merged! As far as the new, more precise tests, I'll add them after all the PRs about AMBER are done (in this way we are certain all PRs are fine, at least for what the current tests cover :-) )
