### ISSUE TITLE
AMBER: testing invalid files all together?

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemlyb#234]
In `test_amber.py` we have a function `test_dHdl_invalidfiles` which simply checks if a bunch of "invalid files" all are read as invalid while parsed.
 
I think this test should be replaced with a proper test for each case of an invalid file, catching the correct exception/warning. This makes it easier if we have to remove a test (for example now not finding a `temp0` section does not throw an error) and much more informative information is obtained when some test will fail.

**Comment by xiki-tempula** [comment]
Yes, I think this is reasonable.
