### ISSUE TITLE
User shouldn't be able to change the estimator attribute

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#246]
As discussed in https://github.com/alchemistry/alchemlyb/issues/244#issuecomment-1264352791
Currently we allow the user to change the attribute in the estimator object. This would mean that the user could do
```python
ti = TI().fit(df)  # df is in kcal/mol
# now  ti.delta_f_, ti.d_delta_f_, and ti.dhdl are all in kcal/mol
ti.delta_f_ = to_kT(ti.delta_f_)
# now the user has an estimator with delta_f_ values in kT and the d_delta_f_ in kcal/mol
```
Example given by @DrDomenicoMarson 
Which could cause confusion, I'm thinking of make all these delta_f_ d_delta_f_ into a property which only has the get method and thus prevent the user from editing them.

Do you think this could cause issues? @orbeckst

**Comment by orbeckst** [comment]
I didn't expect users to change the estimator objects in this way... I don't see an issue with making them properties, especially if this increases robustness.
