### ISSUE TITLE
Default the unit of the plotting function to None

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#247]
As discussed in https://github.com/alchemistry/alchemlyb/issues/244#issuecomment-1264356239
Currently plot_dF_state, plot_ti_dhdl and plot_convergence all have `kT` as default unit. 
This kind of creates extra confusions, as the input estimator or dataframe has already had unit and the plotting function will force them to be `kT`.

I purpose that 

- The unit is default to None and the plotting function will just use the unit already in the estimator or dataframe. If the unit is not None, we would then do the unit conversion.
- Given that we are inputing dataframe to plot_convergence, I'm also thinking of deprecating the unitless array input to plot_convergence to make life easier.

This is partially linked to #246 as currently, the user could change the `delta_f_` and `d_delta_f_`, and then different part of the estimator could have different units. But if the #246 is fixed, we could be sure that the estimator has one unit.

What do you think @orbeckst

**Comment by DrDomenicoMarson** [comment]
I really like this new approach! (I now I was never asked  for an opinion, but I really like it :-) )!

**Comment by orbeckst** [comment]
You (and anyone else using or developing alchemyb) are _always_ welcome to offer opinions and review PRs!!!

Please do hit the "review" button on any PR that you're looking at. Constructive feedback or general agreement is always helpful.

**Comment by orbeckst** [comment]
@xiki-tempula , I like the idea, too.

Sorry for my delayed response, I just missed it. (Thanks to @DrDomenicoMarson comment it appeared again on my radar. See @DrDomenicoMarson , your comment alone is moving us forward ;-) ).

**Comment by DrDomenicoMarson** [comment]
Great! I can't promise that I'll have time in the next few days to work on this, but I'll be happy to contribute if I manage to!
