### ISSUE TITLE
BAR estimator

### ISSUE THREAD

**Issue by ianmkenney** [alchemistry/alchemlyb#28]
Create a BAR estimator that:

1. takes `u_nk` as an argument
2. computes the free energy differences between each state along with their uncertainties

**Comment by dotsdl** [comment]
@ianmkenney can you open a PR with your current BAR implementation? I know it wasn't working quite right yet, but that would allow more eyes to have a look (namely, mine :D).

**Comment by orbeckst** [comment]
@harlor I am assigning this to you as you've been moving PR #60 forward.

**Comment by harlor** [comment]
BTW - Besides a review is there something else missing in the PR?
