### ISSUE TITLE
Deprecation of AutoMBAR

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#284]
for pymbar 4, MBAR(method='robust') will give the same iterative solver as the current autombar, so autombar should be Deprecate in alchemlyb2 where we introduce pymbar 4.

**Comment by orbeckst** [comment]
ok, we'll add it to 1.0.1 #279

**Comment by orbeckst** [comment]
Actually, let's just remove AutoMBAR from alchemlyb 2.0. 

We keep in 1.x but it's not needed for 2.0.
