### ISSUE TITLE
intersphinx links to pymbar do not resolve

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#297]
Links to the docs of pymbar such as the ones in the _See Also_ box

```
 pymbar.timeseries.statistical_inefficiency
    detailed background

 pymbar.timeseries.subsample_correlated_data
    used for subsampling
```

in https://alchemlyb.readthedocs.io/en/latest/preprocessing/alchemlyb.preprocessing.subsampling.html#alchemlyb.preprocessing.subsampling.statistical_inefficiency do not resolved.

- [ ] check intersphinx linking (did the pymbar docs change where their objects.inv is located?)
- [ ] check docs for missing links in other parts

**Comment by xiki-tempula** [comment]
Sorry, what do you mean that it won't resolve?
I checked these two `pymbar.timeseries.statistical_inefficiency` and `pymbar.timeseries.subsample_correlated_data` and they do go to the correct pymbar page?

**Comment by orbeckst** [comment]
well. I agree, it seems to work (now?)
