### ISSUE TITLE
The dE method in decorrelating the u_nk data is not actually dE

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#299]
Fro Gromacs each column in the u_nk is the dE between the reduced potential of the current lambda (the lambda of the column) and the reduced potential of the lambda that is being simulated. So for the dE method in decorrelation, we just use the column after or before the current lambda as it is already dE.

However, this assumption is not always the case particularly when one wants to use the function to decorrelate the openmmtools output where one could just put in a dataframe where each column is the reduced potential of that lambda window. In this case, the decorrelation will be based on the reduced potential instead of dE.

**Comment by xiki-tempula** [comment]
It seems that this is an issue for amber as well.

**Comment by orbeckst** [comment]
Note for anyone looking at this issue to understand how PR #300 changed the behavior, see https://github.com/alchemistry/alchemlyb/pull/300#issuecomment-1476630207
