### ISSUE TITLE
need CI

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#3]
- [ ] set up travis to run tests #2
- [ ] coverage or coveralls

**Comment by dotsdl** [comment]
We should be good to go here @ianmkenney in terms of permissions on the repo.

**Comment by ianmkenney** [comment]
It looks like you have to set it up, I don't have admin rights. If you can just add it, I should be able to take it from there.

**Comment by dotsdl** [comment]
Done. `alchemlyb` is now activated on Travis.

**Comment by davidlmobley** [comment]
@ianmkenney do you need admin access?

**Comment by ianmkenney** [comment]
@davidlmobley it doesn't look like I do just yet. I think I should be good for now

**Comment by ianmkenney** [comment]
@davidlmobley Sent a request to hook into codecov.io for coverage reporting

**Comment by dotsdl** [comment]
@ianmkenney is this all working now? Can we close?

**Comment by dotsdl** [comment]
CI is working via Travis. Thanks @ianmkenney!
