### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#305]
@orbeckst Shall we do a new release before we switch to the new logger?
There has been a bug fix so worth a new release.

----

For a [release](https://github.com/alchemistry/alchemlyb/wiki/Developer-Guide#release-management)
- [x] finalize CHANGES
- [x] tag 2.0.1 (triggers upload to test.pypi)
- [x] test release from test.pypi.org
- [x] make GitHub release (triggers upload to pypi)
- [x] check [conda-forge feedstock}(https://github.com/conda-forge/alchemlyb-feedstock/)

**Comment by orbeckst** [comment]
yes -- sounds good. If it's just bug fixes it can be 2.0.1On Apr 5, 2023, at 6:36 AM, Zhiyi Wu ***@***.***> wrote:﻿
@orbeckst Shall we do a new release before we switch to the new logger?
There has been a couple bug fix so worth a new release.

**Comment by xiki-tempula** [comment]
@orbeckst Do you mind have a look at the doc fix https://github.com/alchemistry/alchemlyb/pull/307? I will make a new release after the doc fix. No rush.

**Comment by orbeckst** [comment]
I added a check list at the top of the issue. Close the issue when all are checked. The conda-forge package may take a while.

**Comment by xiki-tempula** [comment]
@orbeckst Sorry, Do you mind deleting the package 2.0.2, 2.0.1, 2.0.1.dev2, 2.0.1.dev1 from test pypi? I think you are the maintainer.

**Comment by orbeckst** [comment]
@xiki-tempula I invited you on pypi but on test.pypi you first need to create an account. Then you can do the maintenance yourself.

Btw, deleting the package will not help. We are not able to reupload with the same version.

**Comment by orbeckst** [comment]
At least that's what test.pypi tells me:

> Warning This action cannot be undone!
> 
> You will not be able to re-upload a new distribution of the same type with the same version number.
> 
> Deletion will break any downstream projects relying on a pinned version of this package. It is intended as a last resort to address legal issues or remove harmful releases.
> 
> Consider [yanking](https://test.pypi.org/help/#yanked) this release, making a new release or a [post release](https://test.pypi.org/manage/project/alchemlyb/releases/#delete_release-modal-1) instead.

**Comment by xiki-tempula** [comment]
Thanks, I never realised that one needs a separate account for test pypi. I have created one now, do you mind add me as a minatiner?

> Btw, deleting the package will not help. We are not able to reupload with the same version.

I see. Thanks. I have modified the https://github.com/alchemistry/alchemlyb/wiki/Developer-Guide to do the testing in *.*.*.rc1 format and only tag it as *.*.* when the test on pypi succeed.

**Comment by orbeckst** [comment]
I am trying to add you to testpypi but get

> User 'wuzhiyi' does not have a verified primary email address and cannot be added as a Maintainer for project

Thanks for updating release guide, good idea.

**Comment by xiki-tempula** [comment]
@orbeckst Thanks, I have just created that account, it shall be fixed now.
