### ISSUE TITLE
create roadmap

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#31]
On the Skype call on 2017-10-16 we agreed to come up with a preliminary roadmap (for the next call in two weeks).

Please add to the [Roadmap](https://github.com/alchemistry/alchemlyb/wiki/Roadmap) wiki page.

General discussion in this issue. If you want to be kept up to date, just subscribe or comment on this issue.

cc @mrshirts @davidlmobley

**Comment by brycestx** [comment]
Looks like I can not edit the [Roadmap](https://github.com/alchemistry/alchemlyb/wiki/Roadmap) wiki page. Please add permissions to push changes to @brycestx @shuail and @marcelschumann2

**Comment by davidlmobley** [comment]
Permissions added. I'm going to look at this shortly too.

**Comment by davidlmobley** [comment]
@mrshirts - you had a student who would be involved too?

**Comment by orbeckst** [comment]
We have a basic roadmap set up at https://github.com/alchemistry/alchemlyb/wiki/Roadmap . Please continue editing the wiki page as necessary. 

If you need edit permission please feel free to ask here (or raise a new issue.)
