### ISSUE TITLE
codecov badge shows coverage from PR and not master

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#33]
For some reason, our codecov badge https://codecov.io/gh/alchemistry/alchemlyb shows the coverage from a PR (in this case 49% from #32) instead of master (which should be around 90%).

Look into how codecov does things.

**Comment by dotsdl** [comment]
I think this is due to [this issue on codecov's end](https://github.com/codecov/support/issues/448). If the PR is coming from a fork's `master` branch, codecov gets confused.

**Comment by orbeckst** [comment]
Thanks. Any ideas how to deal with it?

**Comment by davidlmobley** [comment]
Maybe we can bypass (though not resolve) by getting people to do PRs from branches rather than forks. But that is not a general solution.

**Comment by orbeckst** [comment]
As I understand it, the problem only occurs if they do a PR from a branch called *master* on the fork. If they follow normal procedures and create a branch first and do the PR from the branch, the codecov will not become confused. (In fact that is what works for us everywhere else.)

**Comment by dotsdl** [comment]
Not sure this one can be solved by us; it shouldn't generally crop up if PRs don't come from `master` on a fork. Closing for now; reopen if needed.
