### ISSUE TITLE
error when running abfe workflow-possible installation issue

### ISSUE THREAD

**Issue by lwhitm1** [alchemistry/alchemlyb#335]
I Installed alchemlyb using conda (conda install -c conda-forge alchemlyb). I then encountered a module not found error for alchemtest, which I pip installed into the environment.

I get the following error when attempting to run the abfe workflow:

Traceback (most recent call last):
  File "C:\Users\whitm\research_rotations\shirts-research-rotation\testing\methyl_benzene\analysis\reg\local_run.py", line 11, in <module>
    workflow.run(skiptime=100, uncorr='dhdl', threshold=50,
  File "C:\Users\whitm\anaconda3\Lib\site-packages\alchemlyb\workflows\abfe.py", line 275, in run
    self.estimate(estimators)
  File "C:\Users\whitm\anaconda3\Lib\site-packages\alchemlyb\workflows\abfe.py", line 450, in estimate
    self.estimator[estimator] = BAR(**kwargs).fit(u_nk)
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whitm\anaconda3\Lib\site-packages\alchemlyb\estimators\bar_.py", line 111, in fit
    uk1 = groups.get_group(self._states_[k + 1])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whitm\anaconda3\Lib\site-packages\pandas\core\groupby\groupby.py", line 800, in get_group
    raise KeyError(name)
KeyError: 0.2

The contents of the analysis script are attached.
[local_run.txt](https://github.com/alchemistry/alchemlyb/files/12885921/local_run.txt)

I have attempted to do fresh installs of alchemlyb both on the compute cluster and locally on my own pc, but the issue persists. 

Is there a way to install alchemlyb without having to install alchemtest as a separate task? Or, is there a way to conda install alchemtest?

**Comment by xiki-tempula** [comment]
The error that you got seems to BAR cannot handle the input. I wonder if I can have your input data to have a test, please? Thank you.

**Comment by lwhitm1** [comment]
> @lwhitm1 Thanks for the report. When you say
> 
> > I then encountered a module not found error for alchemtest, which I pip installed into the environment.
> 
> What do you mean? Do you need alchemtest for your production run?

After doing a fresh conda install of alchemlyb and attempting to do analysis, I run into this error. 
![image](https://github.com/alchemistry/alchemlyb/assets/143537557/75f925ea-9b46-4452-92be-e2438da25e18)

**Comment by xiki-tempula** [comment]
Why do you need to do `from alchemtest.gmx import load_ABFE`
If you try to import alchemtest then you need to be installed.

**Comment by lwhitm1** [comment]
> The error that you got seems to BAR cannot handle the input. I wonder if I can have your input data to have a test, please? Thank you.

My input data for this analysis attempt lives here: https://github.com/lwhitm1/shirts-research-rotation/tree/main/testing/methyl_benzene/create_lambdas

**Comment by xiki-tempula** [comment]
> Can I run the workflow without loading it?
Yes.
I load them in this page as I need the data from somewhere.

**Comment by lwhitm1** [comment]
> ```
> from alchemlyb.workflows import ABFE
> ```
> 
> loads example data. If you use your own data, then you won't need it. You need to adapt the example to your own needs, i.e., `dir` need to contain _your_ data.


I'm a bit confused about how to use the automatic workflow with my data then (how do you import the automatic workflow infrastructure to work with your data if from alchemlyb.workflows import ABFE loads the example data?). I had dir set to the path where my data is. 

I apologize for the rudimentary questions.

**Comment by orbeckst** [comment]
SORRY!

(I'll add a note to my previous entry.)

**Comment by lwhitm1** [comment]
I found the error in my production simulation script and was able to rerun and actually sample each state. The analysis script also works. Thank you for your help!

**Comment by orbeckst** [comment]
Great that everything is working now. I am closing the issue.

Note for the future that we have the [discussion forum](https://github.com/alchemistry/alchemlyb/discussions) for general questions.
