### ISSUE TITLE
2.2.0 release

### ISSUE THREAD

**Issue by xiki-tempula** [alchemistry/alchemlyb#344]
I think we are good to do another release. The most important bit would be that the metadata is now fully conserved during reading and saving so shall be a lot more robust.

**Comment by orbeckst** [comment]
@xiki-tempula do you have a bluesky account, in case I get to do a release post ?

**Comment by xiki-tempula** [comment]
@orbeckst Sorry I don't. Just cannot keep up with all these social media things.

**Comment by orbeckst** [comment]
That’s fine and completely understandable. Am 4/7/24 um 12:59 schrieb Zhiyi Wu ***@***.***>:﻿
@orbeckst Sorry I don't. Just cannot keep up with all these social media things.
