### ISSUE TITLE
Docs clarification relating to matrix?

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemlyb#347]
It's been a while since I saw direct alchemlyb results from anyone, and a new student in my lab was recently showing me some output in the form of a matrix, like those shown here: https://alchemlyb.readthedocs.io/en/latest/estimators-fep.html (see e.g. the `mbar_coul.delta_f_` output).

It was a little confusing to me as to why we're seeing a full matrix rather than a simple set of estimated pairwise free energy differences -- e.g. what are the rows and what are the columns in the output? -- so I had her refer me to the docs and I didn't find them particularly helpful. Perhaps this could be clarified? Additionally, this phrase is not that clear either:

> The sum of the endpoint free energy differences will be the free energy of solvation for benzene in water. 

as it hasn't said yet (though it does say it further down) what ARE the endpoint free energy differences. 

I think my request would be to just clarify this documentation a bit -- what exactly is this matrix being displayed, and what (if anything) would I typically want to do with it? Maybe give an appropriate reference to a paper and equation? I'm sure I'm overlooking something simple but I don't recall ever having seen it written this way before. I THINK I can make a good educated guess about what's actually being displayed, but looking at the docs from the perspective of my newer student it's extremely opaque.

**Comment by xiki-tempula** [comment]
I will add a line saying that the `mbar_coul.delta_f_[i, j]` will be the `G_j - G_i`

**Comment by davidlmobley** [comment]
That will help somewhat, though it's still unclear to me -- is this information completely redundant across rows in the matrix? e.g. if it's always G_i - G_j why do I need multiple rows printed out?

**Comment by xiki-tempula** [comment]
I do agree that the information is redundant, you only need G_i - G_{i-1} and can then construct all the dG out of it.
I think one reason that we adopt this formalism is that it is clear, if you want G_1 - G_0, the result is just mbar.delta_f_.loc[0.00, 1.00]. If you want the dG between any two lambda values, you could just get it directly from the matrix.

**Comment by davidlmobley** [comment]
Ah, OK, I see. That makes sense. Can you put that in the docs too?

**Comment by orbeckst** [comment]
@xiki-tempula are you able to take updating the docs on? I'll assign the issue to you but if you can't get to it, please unassign yourself.

Of course, anybody else is also welcome to just jump in. (I just don't have much time this moment to get started.)
