### ISSUE TITLE
[JOSS] inconsistent author list between docs and AUTHORS

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#383]
As pointed out in https://github.com/openjournals/joss-reviews/issues/6934#issuecomment-2249664394 , the authors in the doc footer 

![image](https://github.com/user-attachments/assets/561f6648-7705-4973-81d1-7ecc18abe208)

do not include all the authors in [AUTHORS](https://github.com/alchemistry/alchemlyb/blob/master/AUTHORS), which is the authoritative reference for all code contributors. 

We should either include everyone in the doc footer (generate the list for the docs programmatically) or simply link to the AUTHORS file.

**Comment by orbeckst** [comment]
I am in favor of just stating as authors "The [alchemlyb development team](https://github.com/alchemistry/alchemlyb/blob/master/AUTHORS)." with a link to AUTHORS.

**Comment by xiki-tempula** [comment]
@orbeckst I do see the point as it will be painful to maintain a up-to-date AUTHORS. But how shall we fix this? Sorry the suggestion is not too clear to me.

**Comment by orbeckst** [comment]
I'll have a look, I've done something similar for other projects.--Oliver Beckstein * ***@***.***://becksteinlab.physics.asu.eduOn Jul 27, 2024, at 12:01 PM, Zhiyi Wu ***@***.***> wrote:﻿
@orbeckst I do see the point as it will be painful to maintain a up-to-date AUTHORS. But how shall we fix this? Sorry the suggestion is not too clear to me.
