### ISSUE TITLE
fix dates in CHANGELOG

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#388]
The dates in CHANGELOG _should_ be MM/DD/YYYY but some of them are clearly DD/MM/YYYY: need to check when we released in https://github.com/alchemistry/alchemlyb/releases and then fix CHANGELOG retroactively.

**Comment by xiki-tempula** [comment]
I think it is always DD/MM/YYYY? Which country does MM/DD/YYYY?

**Comment by orbeckst** [comment]
The US!! And this is what’s written at the top of the file. Am 8/19/24 um 16:59 schrieb Zhiyi Wu ***@***.***>:﻿
I think it is always DD/MM/YYYY? Which country does MM/DD/YYYY?
