### ISSUE TITLE
change the subsampling method to use pymbar.timeseries.subsampleCorrelatedData() 

### ISSUE THREAD

**Issue by shuail** [alchemistry/alchemlyb#39]
Proposed to change the subsampling method to avoid using the pandas slicing for subsampling, this issue is corresponding to the pull request #38 

The pandas slicing method requires the steps to be integer which is rounded from the statistical inefficiency of a time series. This will sometimes make different time series indistinguishable from each other in terms of their subsampling positions. Proposed to switch to the pymbar subsampleCorrelatedData function.

**Comment by orbeckst** [comment]
The discussion on PR #38 lead to the following consensus (see comments by @davidlmobley  @shuail and myself leading up to https://github.com/alchemistry/alchemlyb/pull/38#issuecomment-344782900):

- [ ] use `pymbar.timeseries.subsampleCorrelatedData()` for fractional `g` or `ceil(g)`
- [ ] add a keyword to allow the user to switch between `conservative=True` and `False` 
- [ ] make the **default** `conservative=True`
