### ISSUE TITLE
new release 2.4.0 for JOSS paper

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#396]
Once we have the citations added #394 for the JOSS paper PR #328 , we need another ~~patch~~ release to update the zenodo archive.

(Because PR #381 was merged with a new feature, we need to make it a new minor release.)

**Comment by orbeckst** [comment]
Merge PR #397 before making a release.

**Comment by xiki-tempula** [comment]
release done

**Comment by orbeckst** [comment]
Thanks for making the release!
