### ISSUE TITLE
Pip installable

### ISSUE THREAD

**Issue by rhheilma** [alchemistry/alchemlyb#4]
Need to make pymbar pip installable

**Comment by davidlmobley** [comment]
@mrshirts - comments on this?

**Comment by davidlmobley** [comment]
(Note, however, @rhheilma , that `pymbar` IS `conda` installable.)

**Comment by dotsdl** [comment]
I think this is an out-of-date issue. Installing `alchemlyb` with `pip` from the source tree works just fine, with no issues from `pymbar` (`alchemlyb` requires `pymbar` 3.0, which [got pushed to PyPI last month](https://github.com/alchemistry/alchemlyb/pull/5#issuecomment-269866181). I believe I can close this for now.

Once we have a release (next two weeks for an alpha), `alchemlyb` will be `pip` installable from PyPI.
