### ISSUE TITLE
Pylint alerts corrections as part of intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [alchemistry/alchemlyb#419]
I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/)  alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking your approval for conducting the interventions in your repositories.The interventions are expected to benefit the project and will submitted in PR for approval.

See examples of interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

See the [planed internetions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/candidates/alchemistry_alchemlyb_interventions_October_05_2024.csv).

Is it OK if I'll fix the alerts?

**Comment by xiki-tempula** [comment]
I did have a thought of linting but wouldn't ruff be a better call? pylint is not so popular these days.

**Comment by evidencebp** [comment]
I was not familiar with ruff, thank you for letting me know @xiki-tempula , I'll check it.
However, this experiment is on pylint.

Regarding the use of linters, they might help to improve the code significantly.
However, they tend to produce a lot of alerts, making fixing all of them too time consuming.
The goal of this experiment is to build a dataset of fixes and to evaluate their benefit.

The experiment can allow you to see the fixes on your code and their value (and I'll be happy to know what you think of them).
However, note that for the experiment we consider only files that were recently modified and split the files into intervention and control.
This means that there will probably be other alerts that won't be fixed.

So, can I do the interventions?

**Comment by xiki-tempula** [comment]
I kind of prefer to do it with ruff. I'm happy if you want to do it with ruff but I don't think anyone uses pylint, so I don't want to do something that makes pylint happy but makes other linting tools unhappy.

**Comment by evidencebp** [comment]
I understand your concern.
Linters are based on software engineering insights and alerts of ones are usually not considered good by other linters.

As you can see in the [planed internetions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/candidates/alchemistry_alchemlyb_interventions_October_05_2024.csv), there are 10 alerts.
There types are: line-too-long, too-many-branches, unnecessary-pass, pointless-statement, and too-many-statements.
All these alerts are rather canonical.
Since ruff has 800 alerts, I'm rather sure it alerts on all these and more.

Also, the benefit of the project is a main concern.
When I notice a false alert, I do not modify the code and the alert is labeled as less beneficial.

**Comment by xiki-tempula** [comment]
I think it would be good to do all the linting fix in one go. But I think you could do a PR and I could see if we can merge it.

**Comment by evidencebp** [comment]
Great.

**Comment by evidencebp** [comment]
@xiki-tempula, please see the [PR](https://github.com/alchemistry/alchemlyb/pull/420) with the alert fixes.
I did not find requirements files so I could not run the code.
Can you consult me on that?

I would like to also consult you regarding two alerts, which I did not fix yet.

In src\alchemlyb\workflows\base.py, the method plot is empty with just pass.
I was not sure if it was forgotten (and goog alert) or overridden in sub-classs
.If it should be overridden it might be better to raise NotImplemented exception to enforce implementation in all sub-classes

In src\alchemlyb\preprocessing\subsampling.py, there is an alert in line 189 on 
df[key]
whose value is not used.
It seems that statement is needed in order to see if the key exists.
However, won't you prefer to check directly with key in df.columns?

**Comment by evidencebp** [comment]
Oh, I see that some test fail due to my changes.
Sorry, I'll check that.

**Comment by evidencebp** [comment]
There were two faliures which I fixed.

The first was in src\alchemlyb\visualisation\dF_state.py
The value of mnb is not set in the case of landscape orientation.
It was like that even before extracting get_determine_orientation.
However, now that this is a separated function, the test fails due to returning an unset variable.

This might detect a bigger bug regarding not setting it unintentionally.

The other was in src\alchemlyb\workflows\abfe.py which pass now.

I also get slightly [less coverage](https://app.codecov.io/gh/alchemistry/alchemlyb/pull/420?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alchemistry)

This is due to untested exception raising code.
It was not tested before too yet now in the extraced functions it is considered as a new line (while it is actually a moved uncovered line).

**Comment by evidencebp** [comment]
I noted that the CI [failed](https://github.com/alchemistry/alchemlyb/actions/runs/11080818620) on the same problem regardless of my PR.

**Comment by evidencebp** [comment]
@xiki-tempula , are you satisfied with the PR?
Are there things I should modify or clarify?

**Comment by xiki-tempula** [comment]
I'm happy with the fix which fixes line too long.
But I'm concerned with regard to putting part of the function into another function.
The separation doesn't seems logic to me and kind of reduces the readability.

**Comment by evidencebp** [comment]
This is a good start already.

Regarding the spliting, I tried to chooce code parts that are
- Already in the same sequence (not trying to reuse/merge duplicated code)
- Have a resonable logic that I can identify (and use as the function name)
- When possible, having comments supporting the above

In general, it is recommended to split to code into small units having a single goal.
The readbility is considered to be increased since you read the functionality and not the implementation details unless they are relevant.

Are there cases in which you are ok with the splitting?

**Comment by evidencebp** [comment]
@xiki-tempula , would you like me to create anew PR, without the splitting, so you will be OK with merging it?

**Comment by evidencebp** [comment]
Great, I created a dedicated [PR](https://github.com/alchemistry/alchemlyb/pull/424)
@xiki-tempula
