### ISSUE TITLE
AMBER FEP parser

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#42]
In line with the overall [API proposal](http://alchemlyb.readthedocs.io/en/latest/api_proposal.html), we want to have parsers for each of the major MD engines, and eventually have coverage for all of those in use. For Amber we already have a TI parser (#10), we still need an "MBAR/FEP" parser:

- [ ] Extracting reduced potentials `u_nk` from output files (for FEP).

This issue is the nexus for discussion for such parsers for the **AMBER** package. If you have existing parsing code for this package, comment below and we can begin adapting it into the parsers outlined above in a PR.

**Comment by orbeckst** [comment]
@shuail @brycestx is this issue something that you're actively working on or are committed to doing? (Which would be great!)

If not then it's ok to un-assign yourselves to make clear that really anyone can grab the issue and work on it.

**Comment by brycestx** [comment]
First pass located at #51
