### ISSUE TITLE
docs for Gromacs extended ensemble parsers

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#49]
With #14 fixed (in PR #48), I just realized that we should also be more explicit in the docs for the [Gromacs parser](https://alchemlyb.readthedocs.io/en/latest/parsing/alchemlyb.parsing.gmx.html) what kind of data formats we're actually parsing.

@mrshirts @trje3733 could you please edit [docs/parsing/alchemlyb.parsing.gmx.rst](https://github.com/alchemistry/alchemlyb/blob/master/docs/parsing/alchemlyb.parsing.gmx.rst) and describe the extended ensemble formats? (you might be able to edit the file via GitHub and make a PR from the browser).

**Comment by orbeckst** [comment]
@trje3733 @mrshirts do you want to give this issue a try before the call on Monday?

**Comment by davidlmobley** [comment]
Ping, @mrshirts and @trje3733 - is this something you don't have time to do or don't think is important? If not, is it on your radar?

Thanks.

**Comment by trje3733** [comment]
@orbeckst, sorry about the delay. I'll take care of this in the next day or two.

**Comment by orbeckst** [comment]
Closed with PR #50

**Comment by orbeckst** [comment]
Thanks @trje3733 !
