### ISSUE TITLE
remove gitter

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#52]
We have a gitter channel associated with alchemlyb (see the badge in the README) but we are not using it.

I would remove the badge and close the channel and for right now 
- use the issue tracker for user input, 
- the wiki for notes, and 
- email to coordinate between developers/stake holders. 

We can revisit if the situation changes but I don't like opening too many channels because that just gets exhausting and will invariably disappoint someone who thinks that, in this case, gitter is a standard way to communicate with the project.  

Opinions @davidlmobley @mrshirts ?

**Comment by davidlmobley** [comment]
SGTM. I don't know what it is yet. Ha. :)

**Comment by orbeckst** [comment]
removed in PR #55
