### ISSUE TITLE
new release 0.2.0

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#53]
We reached the ["Immediate/Pressing" milestones in our roadmap](https://github.com/alchemistry/alchemlyb/wiki/Roadmap#immediatepressing-requirements) and have a whole bunch of new features as well as really good testing coverage.

I'd like to release a 0.2.0 once the latest Amber parser changes are in. (If we can get a NAMD parser, too, then that would be a bonus, but I don't know what the time line is for that)

Is there anything else that we need to take care of, @alchemistry/alchemlyb ?

**Comment by orbeckst** [comment]
I'd also like to remove the ["alpha state" warning](https://alchemlyb.readthedocs.io/en/latest/#alchemlyb-the-simple-alchemistry-library)

> This library is in an alpha state. The library and the documentation is incomplete. Use in production at your own risk.

Some of us are using alchemlyb in a production environment already and the tests and docs are reasonable. 

Instead I like to add something along the lines that we welcome user input, especially in the form of bug reports, feature requests, and questions and that they should please use the issue tracker. I would also say that the library is still in development; our releases use [semantic versioning](https://semver.org/) so that users can immediately see what is happening in a release.

I'll also start a CHANGELOG.

**Comment by davidlmobley** [comment]
@vtlim do you want to comment on timing for NAMD parser? This is really "no pressure" -- we're not in a rush to have it in, so we're interested in knowing when you think you would be likely to get to it, and NOT trying to apply pressure to get it done.

**Comment by orbeckst** [comment]
The release is blocked on
* #56 
* #57 

We can ship something without the NAMD parser #7 so I removed it from the milestone.

**Comment by orbeckst** [comment]
Everything is ready for a 0.2.0 release. I'll try to make a little bit of time by the end of the week to get it out.

**Comment by dotsdl** [comment]
Thanks @orbeckst! Please let me know if there's anything I can do to help; I don't recall if we shared PyPI permissions for publishing packages there.

**Comment by dotsdl** [comment]
Just checked, and currently I'm the sole collaborator on the PyPI package. If you can send me your PyPI username I can add you as an owner as well.

**Comment by orbeckst** [comment]
https://pypi.org/user/Oliver.Beckstein/

**Comment by dotsdl** [comment]
Done!

**Comment by orbeckst** [comment]
alchemlyb and alchemtest 0.3.0 are released.

(Yes, it should have been 0.2.0 but I accidentally labelled alchemtest already as 0.3.0 and then alchemlyb followed suite. There's no deeper reason. With semantic versioning this is not going to be a problem, we just can't backdate anything.)

**Comment by dotsdl** [comment]
Thanks @orbeckst! I think 0.3.0 is totally appropriate. Thanks for pushing it through!
