### ISSUE TITLE
Amber TI parser should provide dimensionless dH/dl

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#57]
The current implementation of the Amber TI parser ([amber.extract_dHdl](http://alchemlyb.readthedocs.io/en/latest/parsing/alchemlyb.parsing.amber.html#alchemlyb.parsing.amber.extract_dHdl)) returns a dataframe with native Amber units (as used to be the case in alchemical-analysis) instead of the [prescribed reduced dHdl standard form](http://alchemlyb.readthedocs.io/en/latest/parsing.html#dhdl-standard-form): the potential energy derivatives should be divided by 1/kT.

See for example https://github.com/alchemistry/alchemlyb/blob/e5b2e581528769a205cab17dfae7d1b9b2f8f2f5/src/alchemlyb/parsing/gmx.py#L132

Todo:
- [ ] `amber.extract_dHdl()` needs additional temperature `T` argument
- [ ] make data dimensionless (something like `dHdl = beta * dHdL` with `beta = 1/(kB*T)`
- [ ] adjust tests

(See also #56 )

**Comment by orbeckst** [comment]
@shuail sorry, this slipped through when I was reviewing earlier. We need to make sure that all parsers produce the same dataframes, though, so this is a necessity.

**Comment by shuail** [comment]
Got it, will take a look soon

**Comment by orbeckst** [comment]
@dotsdl I know you're busy (GitHub displays status nowadays?!?) but because we talked about it, I am tentatively assigning you to this issue and #56 . Maybe @shuail can give input when needed.
