### ISSUE TITLE
Switching Travis CI to Xenial (Ubuntu 16.04) gives different statistical inefficiency test results

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemlyb#66]
I recently tried changing our [Travis CI](https://github.com/alchemistry/alchemlyb/blob/master/.travis.yml) configuration to use `dist: xenial` so that we could add testing against Python 3.7. I've made this into a PR (#65), since it gave errors that will require some discussion to resolve.

From what I can see, we get the following failures:
1. It looks like the change in underlying Ubuntu version gives different results for statistical inefficiency slicing.
2. For Python 3.7, the Amber parsers throw exceptions related to their use of generators.

We'll need to resolve these in the PR before merging to master.

**Comment by harlor** [comment]
For 2. see https://github.com/alchemistry/alchemlyb/pull/69

**Comment by dotsdl** [comment]
Resolved with #65.
