### ISSUE TITLE
Nonequilibrium calculations/BAR estimator?

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemlyb#70]
Has overlap with #28 , but we're working on some nonequilibrium free energy calculations (in GROMACS), which will require a BAR estimator. OK with us adding one? I would have to think some about whether a single BAR estimator can easily handle both nonequilibrium calculations, but it does within `pymbar` so it seems like it should be straightforward enough. @mrshirts may have input.

This is with @hannahbaumann . It would probably also be good to have input form @orbeckst , @harlor and @dotsdl .

**Comment by hannahbaumann** [comment]
It looks like we'd only need a function that gives us the integrated work values for every transition of the nonequilibrium calculation and put those into a DataFrame that can be read as u_nk in the BAR estimator.

**Comment by mrshirts** [comment]
Nonequilibrium should be handled by BAR the same as equilibrium calculations - it's just the reader you would need to change.  Let me know if any other questions that come up.

**Comment by hannahbaumann** [comment]
No, I don't need an autocorrelation analysis!

**Comment by orbeckst** [comment]
Given that #28 has been closed we can also close this issue. Please re-open if necessary or open a new issue if there are problems with BAR. Thanks.
