### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#71]
Write a short software paper on alchemlyb/alchemtest for [JOSS](http://joss.theoj.org/).
- [Author instructions](https://joss.readthedocs.io/en/latest/submitting.html) – create a repo and then submit, ~1000 words, see examples
- authors? 
  - any contributor (name on a commit)
  - must edit and ok paper
  - willing to help with revisions (paper/code/docs)

A JOSS paper does not really pre-empt a full scientific paper (such as a "Best practices in free energy calculations" for LiveCOMS, unless this is already in the works) but it would put a citable "stake in the ground".

Opinions @davidlmobley @mrshirts @brycestx @shuail @harlor @dotsdl @alchemistry/alchemlyb ?

**Comment by mrshirts** [comment]
I'm up for it.  I apologize for my somewhat slow response rates recently.  I'm invested in making sure there's a long term replacement for alchemical-analysis.  Am teaching a new class, so response rate will stay a bit slow for a couple of months for larger coding things.

**Comment by davidlmobley** [comment]
Sounds good to me.

**Comment by harlor** [comment]
Sounds good to me too! Please, let me know if there's anything I can help you with

**Comment by orbeckst** [comment]
The paper was published today https://github.com/openjournals/joss-reviews/issues/6934#issuecomment-2376846523 as https://doi.org/10.21105/joss.06934 .
