### ISSUE TITLE
NAMD parser does not take temperature as argument

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemlyb#75]
The NAMD parser #7 (for FEP) does not take `T` as an argument and does not return `u_nk` in proper units of kT.

**Comment by orbeckst** [comment]
I assume for right now that NAMD writes out energies in **kcal/mol**, based on [NAMD 2.13: NAMD configuration parameters : Output Files](http://www.ks.uiuc.edu/Research/namd/2.13/ug/node12.html#SECTION00062200000000000000)

> The standard units used by NAMD are Angstroms for length, kcal/mol for energy, Kelvin for temperature, and bar for pressure. 

@vtlim @mrshirts can you confirm that the energies in NAMD FEP files are in kcal/mol (in particular our test files in the [tyr2ala dataset](https://alchemtest.readthedocs.io/en/latest/namd.html))?

**Comment by vtlim** [comment]
The energies in the NAMD FEP output files are in kcal/mol. The output file also includes a column for temperature for the present configuration. Could that lead to a difference causing the assertion error?

**Comment by orbeckst** [comment]
Thanks for confirming.

Currently, the temperature from the output file is not used, is it?

I don't think that it would be correct to use the instantaneous temperature for kT – the Boltzmann factor comes from a Lagrange multiplier for system at constant T (i.e., constant average temperature) so this T should be the "target temperature" of the thermostat in the simulation. But maybe @mrshirts @davidlmobley want to correct me here.

**Comment by mrshirts** [comment]
Correct kT is using the target temperature.

Instantaneous "temperature" is a quantity that averages to the target
temperature over a long enough time (or should if things are working
correctly!), but the instantaneous value is not really relevant to
anything.

**Comment by davidlmobley** [comment]
Agreed, yes, that we don't want to use the instantaneous temperature. But we do want to allow people to use the correct temperature in their analysis.

**Comment by vtlim** [comment]
@orbeckst I'm trying to understand where the error is coming from. In the Travis message there are the lines:

```
>       assert X_delta_f[1] == pytest.approx(delta_f, rel=1e-3)
E       assert 10.116843440154604 == 11.0044412521 +- 1.1e-02
```

where 10.117 is approximately the input value for the test from 6.031 kcal/mol, so is this message saying that the internal test is returning about 11 kT?

**Comment by orbeckst** [comment]
@vtlim when you look at
https://github.com/alchemistry/alchemlyb/blob/f095296e15cb54f8748bb4af16e900e946e87402/src/alchemlyb/tests/test_fep_estimators.py#L137-L149 and https://github.com/alchemistry/alchemlyb/blob/f095296e15cb54f8748bb4af16e900e946e87402/src/alchemlyb/tests/test_fep_estimators.py#L98-L103 you see that
- `X_delta_f` is the expected value: 6.031269829 was from the test that you wrote and which passed (and which was in kcal/mol because the NAMD parser used to just work with the  raw energies in kcal/mol); I divided it by  `kT_NAMD` to compare it to the updated NAMD parser, which is supposed to return values in kT.
- `delta_f` is the result of running BAR on the input data

The only real change that I made to `namd.extract_unk` is https://github.com/alchemistry/alchemlyb/blob/f095296e15cb54f8748bb4af16e900e946e87402/src/alchemlyb/parsing/namd.py#L54 If something else is needed or if this is wrong then please feel free to change it.

**Comment by vtlim** [comment]
I think the difference might be [BAR](https://github.com/alchemistry/alchemlyb/blob/4ed712eae9980024d517f353fcd63dfed8c866b4/src/alchemlyb/estimators/bar_.py#L55) should take in reduced energies but the previous answer I provided to the test had the energies in kcal/mol.

**Comment by orbeckst** [comment]
In principle, all we are doing here is attaching different units. I haven't looked at the BAR code itself but the equations should not really care if you were to set "1 kT = 1 kcal/mol".  From the Amber parser and the MBAR I case I know that all that happened was a change of units on the end result.

**Comment by vtlim** [comment]
Might that affect the weighting factors of the BAR algorithm?

**Comment by orbeckst** [comment]
Did your run your data through `alchemical-analysis` and if so, what was the answer and what were the units?

**Comment by vtlim** [comment]
@orbeckst I can try `alchemical-analysis` on other NAMD tutorial datasets to see what those answers are. The original code I used also took in data directly from the NAMD fepout file so those units would also have been kcal/mol.

**Comment by orbeckst** [comment]
Thanks. 

How should we continue here?

**Comment by vtlim** [comment]
I'm not sure the best approach to move forward at the moment. I tested a few different versions on the [NAMD tutorial files](http://www.ks.uiuc.edu/Training/Tutorials/namd/FEP/FEP-tutorial-files/) and saw a range of outputs.
```
source                   tutorial          alc-no reduce    alc-reduce kT (300K)   parseFEP (BAR, T=300K)
----------------------------------------------------------------------------------------------------------
tut02_sphere             -77.6 kcal/mol     -77.1184          -129.4463             -77.4451

tut03_tyr2ala (hydrated) +11.7 kcal/mol       7.1821            12.4539               6.8368
tut03_tyr2ala (isolated)  +4.0 kcal/mol       3.1243             5.2648               3.9506
                          
tut04_crown   (bound)    +61.5 kcal/mol      57.6449            97.1911              57.9465
tut04_crown   (free)     +54.1 kcal/mol      53.4546            89.9684              53.4001
```

**Comment by orbeckst** [comment]
Is _alc-no reduce_ the current alchemlyb NAMD parser that does not return reduced energies whereas _alc-reduce kT_ is the one from PR #76? Is _parseFEP_ the other code?

**Comment by vtlim** [comment]
> Is _alc-no reduce_ the current alchemlyb NAMD parser that does not return reduced energies whereas _alc-reduce kT_ is the one from PR #76? Is _parseFEP_ the other code?

Yes.

> EDIT 2: _tut03_tyr2ala (hydrated)_ is a strange case: it seems to be the only one for which _alc-no reduce_ disagrees substantially from the tutorial value but agrees with _parseFEP_. @vtlim do you know what BAR code the tutorial and `parseFEP` use?

That result was strange to me as well, since the [tutorial file](http://www.ks.uiuc.edu/Training/Tutorials/namd/FEP/FEP-tutorial-files/tutorial-FEP.pdf) says that the data is parsed and analyzed by the ParseFEP in plugin in VMD.

**Comment by orbeckst** [comment]
For a start someone has to go through the BAR equations and figure out what happens when one changes the units.

**Comment by mrshirts** [comment]
The BAR and MBAR operate on dimensionless quantities: kT must be in the same units as the energies.  Otherwise beta*U becomes something different. . . If BOTH the energies and kT change units, then everything is valid, except of course the free energies will be in those different units.  

Currently the software modules assume you are passing in the beta*U quantities (already nondimensionalized).  So you multiply the results by whatever kT you divided the energies by before you passed them into BAR.

**Comment by orbeckst** [comment]
I had a look again and once I converted the new NAMD kT parser values in the table in https://github.com/alchemistry/alchemlyb/issues/75#issuecomment-488838686 to kcal/mol, there's general agreement 
```
                     source  tutorial  alc-no reduce  alc-reduce kT (300K)  parseFEP  alc-reduce kcal/mol (300K)
0              tut02_sphere     -77.6       -77.1184             -129.4463  -77.4451                  -77.170865
1  tut03_tyr2ala (hydrated)      11.7         7.1821               12.4539    6.8368                    7.424532
2  tut03_tyr2ala (isolated)       4.0         3.1243                5.2648    3.9506                    3.138670
3     tut04_crown   (bound)      61.5        57.6449               97.1911   57.9465                   57.941566
4      tut04_crown   (free)      54.1        53.4546               89.9684   53.4001                   53.635672
```
The exception is still the tutorial value for *tut03_tyr2ala (hydrated)* of 11.7 kcal/mol but the independent in-house parser + VMD *parseFEP* also gives 6.8368 kcal/mol so I am inclined to trust the alchemical analysis value. 

When I run the test (`pytest -k TestBAR`) I get for *tut03_tyr2ala (hydrated)* the *alc-reduce kT (300K)* value of 11.0044 kT = 6.5604 kcal/mol. Not sure why this is different from @vtlim 's value but it is similar to the parseFEP value. For now, I adopt **11.0044 ± 0.10234 kT as the alchemlyb reference value**.

With the new reference value the tests should pass.

----

The table was generated from https://github.com/alchemistry/alchemlyb/issues/75#issuecomment-488838686 with the following code:
```python
import pandas as pd
df =  pd.DataFrame({'source': ['tut02_sphere', 'tut03_tyr2ala (hydrated)', 'tut03_tyr2ala (isolated)', 'tut04_crown   (bound)', 'tut04_crown   (free)'], 'tutorial': [-77.6, +11.7, +4.0, +61.5, +54.1], 'alc-no reduce': [-77.1184, 7.1821 , 3.1243, 57.6449 , 53.4546], 'alc-reduce kT (300K)': [-129.4463, 12.4539, 5.2648, 97.1911, 89.9684], 'parseFEP': [-77.4451, 6.8368, 3.9506, 57.9465, 53.4001]})
kB = 1.9872041e-3
kT = kB * 300
df2 = df.assign(**{"alc-reduce kcal/mol (300K)": lambda x: kT*x["alc-reduce kT (300K)"]})
df2
```
