### ISSUE TITLE
Subsampling

### ISSUE THREAD

**Issue by msoroush** [alchemistry/alchemlyb#79]
In order to use subsampling functions, `time` must be used as index name of data frame. In GOMC parser, I am using `step` as index name, which I receive error when I want to use subsampling functions, such as slicing. 
```
KeyError: Index(['time'], dtype='object')
```
One possible solution is to change index name to `time` in GOMC parser. However, generalizing the subsampling module to work with any index name might be useful.

Is it possible to have a function to perform slicing on Concatenate data frame?

**Comment by orbeckst** [comment]
The dataframes are standardized as described in [standard forms of raw data](https://alchemlyb.readthedocs.io/en/latest/parsing.html#standard-forms-of-raw-data) and there "time" has to be included. The standardization is crucial to make all parts of alchemlyb work seamlessly together and changing it might not be easy.

I see two options:

1. You could rename `step` to `time` in PR #78. You should add tests that show that the parsed data can be processed with subsampling and estimators.
2. You could propose a change to all the subsampling and estimator modules to be more flexible with respect to the "time" column. For that, submit a PR that shows that this change is not breaking everything else and we review it then. I won't promise that it will get merged – it looks as if could be a big change with a narrow range of applicability. But that's a discussion we would have on the PR when we see actual code and tests.

(You could argue that we should have included a column `frame` or `step` in addition to `time` in the raw data frame format. However, so far the lack of this column has not prevented the library from doing what it's supposed to. One would need examples where this information would be necessary.)

**Comment by orbeckst** [comment]
Just to add: it would be great to make alchemlyb also work with MC data.
