### ISSUE TITLE
Variance or standard deviation?

### ISSUE THREAD

**Issue by alashkov83** [alchemistry/alchemlyb#90]
In our estimators TI and BAR statistical uncertainty  expressed as variance, but in MBAR - standard deviation?

**Comment by orbeckst** [comment]
Hi @alashkov83 , can you explain how you conclude that the estimators give different uncertainties? 

When I look at the code I see that they all return sqrt(Variance), i.e., standard deviations:
- MBAR: standard deviation https://github.com/alchemistry/alchemlyb/blob/23320fc0180eea9a06672c9097871bfa50cfa060/src/alchemlyb/estimators/mbar_.py#L92 (gets it directly from pymbar.MBAR, namely https://github.com/choderalab/pymbar/blob/d1c18f365fdbe3bbc72d74dc63fe80496cce274b/pymbar/mbar.py#L536 )
- BAR: standard deviation https://github.com/alchemistry/alchemlyb/blob/23320fc0180eea9a06672c9097871bfa50cfa060/src/alchemlyb/estimators/bar_.py#L128 
- TI: standard deviation https://github.com/alchemistry/alchemlyb/blob/23320fc0180eea9a06672c9097871bfa50cfa060/src/alchemlyb/estimators/ti_.py#L97

**Comment by alashkov83** [comment]
Sorry, I did not see this.

**Comment by orbeckst** [comment]
No problem – happy to help.

Perhaps the docs could be clearer, too.
