### ISSUE TITLE
Calculation of statistical inefficiency in the method equilibrium_detection

### ISSUE THREAD

**Issue by wehs7661** [alchemistry/alchemlyb#96]
Hi `alchemlyb` developers, 
When checking the source code of the subsampling methods, I found that the statistical inefficiency was calculated twice in the method `equilibrium_detection`. Here are the relevant lines of code in the method (from line 189 to line 193):
```
# calculate statistical inefficiency of series
statinef  = statisticalInefficiency(series)

# calculate statistical inefficiency of series, with equilibrium detection
t, statinef, Neff_max  = detectEquilibration(series.values)
```
Apparently, the statistical inefficiency calculated in line 190 was immediately overwritten by the one calculated in line 193.   Is line 190 actually redundant? Or is there any other purpose of doing that? Thank you!

**Comment by wehs7661** [comment]
Also, I thought it could be worthy to elaborate on the purposes of using different subsampling methods in the documentation. To my understanding, `equilibrium detection` is the most conservative method, while the method `statistical_inefficiency` can only be used in the situation that the equilibrium region has already been truncated from `df`. I'm not sure if there is any other scenario that `statistical_inefficiency` should be used instead of `equilibrium_detection`, but I thought it would be nice if the documentation could provide some suggestions on this.

**Comment by dotsdl** [comment]
Hi @wehs7661, welcome to `alchemlyb`! I believe you are correct, the first calculation of `statinef` is completely redundant. I'm planning to [show the subsamplers some love](https://github.com/alchemistry/alchemlyb/pull/94#issuecomment-577994716) shortly, and I noticed this one last night too as it happens (and `git blame` puts the blame on me :grin:).

You are welcome to axe the call to `statisticalInefficiency` in a PR as a contribution to the library if you'd like to beat me to it! Thanks for spotting it!

**Comment by wehs7661** [comment]
Hi @dotsdl, thank you so much for your reply! I've already sent a pull request.

**Comment by dotsdl** [comment]
Merged! Thank you @wehs7661!
